### ISSUE TITLE
ARM64 Container Image and usage in a new Project

### ISSUE THREAD

**Issue by mgorfer** [8cH9azbsFifZ/docker-garmindb#1]
Thank you very much for providing GarminDB in a docker container.
I would love to use this on my Raspberry Pi, but there seems to be no ARM64 container image on the host.
Would it be a lot of effort to add the ARM64 image? 

I already built it myself, but I had to update 
`RUN cp /usr/local/lib/python3.11/site-packages/garmindb/GarminConnectConfig.json.example /root/.GarminDb
`
to use python 3.11.

**Comment by mgorfer** [comment]
I would like create a new public repository, which uses GarminDB, InfluxDB, and Grafana, all in a docker-compose setup.

For that, I would like to have a docker image of garmindb, which is available for all platforms.

So there are two options I see for my project.

1. Use your image in my project, if you are okay with that, and if it is possible to add a ARM64 container.

2. Make my own docker image and upload it to docker hub (for example). 
In that case, I would like to know how I can best give you credit for your GitHub repository, because my new repository will not be that different from yours.

I also discussed with the creator of GarminDB already:
https://github.com/tcgoetz/GarminDB/discussions/190

**Comment by 8cH9azbsFifZ** [comment]
Fixed the path and tagged the python version to 3.11 for increased build stability. Update the build pipeline on github for multi-architecture, including arm64.

Nice to read you want to use this repo - go ahead. Feel free to use the new container images and / or contribute :)

Regards:
Gerolf

**Comment by 8cH9azbsFifZ** [comment]
Done
